import Foundation

public enum LegacyIconography: String, Hashable {
    case kakao = "Kakao"
    case background = "Background"
    case logo = "Logo"
    // MARK: Icon
    case menu = "Menu"
    case topArrow = "Arrow"
    case people = "People"
    case mail = "Mail"
    case course = "Course"
    case setting = "Setting"
    case wrong = "Wrong"
    case out = "Out"
    case coin = "Coin"
    case mapPin = "MapPin"
    
    case flag = "Flag"
    case battle = "Battle"
    case shop = "Shop"
    case medal = "Medal"
    case trophy = "Trophy"
    case pen = "Pen"
    
    case clap = "Clap"
    case crying = "Crying"
    case leftStar = "LeftStar"
    case rightStar = "RightStar"
    case talk = "Talk"
    case heart = "Heart"
    case search = "Search"
    case close = "Close"
    case emptyCard = "EmptyCard"
    case cap = "Deathcap"
    case checkStatus = "CheckStatus"
    case closeStatus = "CloseStatus"
    case cardPack = "CardPack"
    case appleLogo = "AppleLogo"
    case googleLogo = "GoogleLogo"
    case airPlane = "AirPlane"
    case cardBackground = "CardBackground"
    case calendar = "Calendar"
    
    // MARK: Achievement image
    case achievementWrongQuiz = "WRONG_QUIZ"
    case achievementUnique = "UNIQUE"
    case achievementSolveQuiz = "SOLVE_QUIZ"
    case achievementShiningCard = "SHINING_CARD"
    case achievementSequencePresent = "SEQUENCE_PRESENT"
    case achievementRuins = "RUINS"
    case achievementPresent = "PRESENT"
    case achievementMakeCourse = "MAKE_COURSE"
    case achievementLevel = "LEVEL"
    case achievementLegendary = "LEGENDARY"
    case achievementFriend = "FRIEND"
    case achievementEpic = "EPIC"
    case achievementCommon = "COMMON"
    case achievementComment = "COMMENT"
    case achievementClearCourse = "CLEAR_COURSE"
    case achievementChallenge = "CHALLENGE"
    case achievementCard = "CARD"
    case achievementCardPack = "CARD_PACK"
    case achievementBuyItem = "BUY_ITEM"
    case achievementBlocks = "BLOCKS"
    case achievementTitle = "TITLE"
    
    case emptyImage = ""
}
